Repository EstSoftOrmi3FinalProject/SchoolTalks-Backend, pull requests merged in 2023-12, with the labels that each got.

#6 자유게시판 CRUD 완성
  accounts/migrations/0004_alter_user_name_alter_user_profile_picture_and_more.py
  accounts/models.py
  post/__init__.py
  post/admin.py
  post/apps.py
  post/migrations/0001_initial.py
  post/migrations/__init__.py
  post/models.py
  post/permissions.py
  post/serializers.py
  post/tests.py
  post/urls.py
  post/views.py
  project/__pycache__/settings.cpython-312.pyc
  project/settings.py
  project/urls.py
  requirements.txt
Labels: enhancement

#11 📝 requirements 수정
  requirements.txt
Labels: documentation

#14 댓글 CRUD PR
  post/admin.py
  post/migrations/0002_alter_post_options_comment.py
  post/migrations/0003_rename_post_comment_post_id.py
  post/migrations/0004_rename_post_id_comment_post.py
  post/models.py
  post/serializers.py
  post/urls.py
  post/views.py
  project/__pycache__/__init__.cpython-312.pyc
  project/__pycache__/settings.cpython-312.pyc
Labels: enhancement

#22 🐛 학년 null=True
  accounts/models.py
Labels: bug

#16 ✨ 자유게시판 좋아요
  post/migrations/0005_like.py
  post/models.py
  post/urls.py
  post/views.py
  project/__pycache__/settings.cpython-312.pyc
Labels: enhancement

#30 26 be 좋아요 정보 전송
  accounts/urls.py
  post/serializers.py
  post/views.py
  project/__pycache__/__init__.cpython-312.pyc
  project/__pycache__/settings.cpython-312.pyc
  project/settings.py
Labels: help wanted

#34 ♻️ user정보 로그인정보로 받아오게하기
  accounts/urls.py
  accounts/views.py
  project/__pycache__/settings.cpython-312.pyc
Labels: help wanted

#40 Fix/post
  post/filters.py
  post/models.py
  post/pagenation.py
  post/tests.py
  post/views.py
Labels: enhancement

#42 Open ai 버전 수정
  aichat/views.py
  project/settings.py
  requirements.txt
Labels: enhancement

#57 Ai Chat
  aichat/tests.py
  aichat/views.py
Labels: enhancement
